---
# tasks file for nginx-app

- import_tasks: installation.yaml
  tags: installation

- improt_tasks: configuration.yaml
  tags: configuration
  
- import_tasks: deployment.yaml
  tags: deployment

- import_tasks: reload.yaml
  tags: deployment,reload
