---
- name: "Install Python3"
  yum: 
    name: python3
    state: presnet 
  
- name: "Download JDK 17.0.2 Binaries"
  get_url: 
    url: "https://download.java.net/java/GA/jdk17.0.2/dfd4a8d0985749f896bed50d7138ee7f/8/GPL/openjdk-17.0.2_linux-x64_bin.tar.gz"
    dest: "/opt/"

- name: "Unpack Java download file"
  unarchive: 
    src: "/opt/openjdk-17.0.2_linux-x64_bin.tar.gz"
    dest: "/opt/"
    copy: no

- name: Stat Java Exist
  stat: 
    path: /opt/jdk-17.0.2
  register: java_stat

- name: create symbolic link jdk-17
  file:
    src: /opt/jdk-17.0.2/
    dest: /opt/jdk-17
    state: link
  when: java_stat.stat.exists == true

- name: Set the JAVA_HOME in /etc/profile file
  lineinfile:
    path: /etc/profile
    state: present
    line: "{{ item }}"
  with_items:
    - 'export JAVA_HOME="/opt/jdk-17"'
    - 'export PATH=$PATH:$JAVA_HOME/bin'

- name: Reload /etc/profile file
  shell:
    cmd: source /etc/profile

- name: Download Node Exporter 
  get_url: 
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.6.1/node_exporter-1.6.1.linux-amd64.tar.gz"
    dest: "/tmp"

- name: Unarchive Node Exporter download file
  unarchive:
    remote_src: yes
    src: "/tmp/node_exporter-1.6.1.linux-amd64.tar.gz"
    dest: "/tmp"

- name: Move Node Exporter Binaries to /usr/local/bin
  copy:
    src: "/tmp/node_exporter-1.6.1.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    remote_src: yes
    owner: root
    group: root
    mode: 0755  

- name: Add Node Exporter service file
  copy:
    src: "node_exporter.service"
    dest: "/etc/systemd/system/node_exporter.service"
  
- name: configure systemd to use service
  systemd:
    daemon_reload: yes
    enabled: yes
    state: started
    name: node_exporter.service