---
# tasks file for nginx-app

- import_tasks: installation.yaml
  tags: installation,all

- import_tasks: configuration.yaml
  tags: configuration,all
  
- import_tasks: deployment.yaml
  tags: deployment,all

- import_tasks: reload.yaml
  tags: deployment,reload,all

- import_tasks: filebeat.yaml
  tags: filebeat,all